<a href="https://colab.research.google.com/github/GitHubrenu/ProgrammingAssignment2/blob/master/Numpy_Exercises1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

In [ ]:
 
arr=np.zeros(10)
print("An array of 10 zeros:")
print(arr)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
 arr2 = np.ones(10)
print("An array of 10 ones:")
print(arr2)

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
 arr5=np.ones(10)*5
print("An array of 10 fives:")
print(arr5)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
 import numpy as np
print("An array of integers from 10 to 50")
arr3 = np.arange(10,51)
print(arr3)

An array of integers from 10 to 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
print("An array of all the even integers from 10 to 50")
arr4=np.arange(10,51,2)
print (arr4)

An array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
print("create a 3x3 matrix with values ranging from 0 to 8")
np.arange(0,9).reshape(3,3)

create a 3x3 matrix with values ranging from 0 to 8


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
print("Create a 3x3 identity matrix"
)
np.eye(3)

Create a 3x3 identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
print("Create an array of 20 linearly spaced points between 0 and 1:")
np.linspace(0,1,20)

Create an array of 20 linearly spaced points between 0 and 1:


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
print("Numpy Indexing and Selection")
matrix = np.arange(1,26).reshape(5,5)
matrix

Numpy Indexing and Selection


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
 matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
 matrix[3,4]

20

In [ ]:
matrix[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
 matrix[4:,0:5]

array([[21, 22, 23, 24, 25]])

In [ ]:
 matrix[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
print ("Get the sum of all the values in matrix")
matrix.sum()

Get the sum of all the values in matrix


325

In [ ]:
print("Get the standard deviation of the values in mat")
matrix.std()

Get the standard deviation of the values in mat


7.211102550927978

In [ ]:
print("Get the sum of all colums in matrix")
matrix.sum(axis=0)

Get the sum of all colums in matrix


array([55, 60, 65, 70, 75])